### ISSUE TITLE
Looks like there's a bug in the UI (29-02-2024)

### ISSUE THREAD

**Issue by AinaSendra** [Pioreactor/pioreactorui#127]
I try to connect to pioreactor.local and i get this error, since 5 hours ago.

Something went wrong with the PioreactorUI!
Don't worry. It's our fault. Here's what you can do:
Looks like there's a bug in the UI. See the below for error information. We would appreciate it if you create an issue in [Github](https://github.com/Pioreactor/pioreactorui/issues) for us, with the information below.

URL: http://pioreactor.local/
Cannot read properties of undefined (reading 'username')

**Comment by CamDavidsonPilon** [comment]
Solution in #130
