### ISSUE TITLE
undefined (reading 'username')

### ISSUE THREAD

**Issue by Eleni-Mavro** [Pioreactor/pioreactorui#130]
URL: http://pioreactor.local/pioreactors
Cannot read properties of undefined (reading 'username')

**Comment by CamDavidsonPilon** [comment]
SSH into your leader, and enter:

```
nano .pioreactor/config.ini
```



This is your config.ini that you also see in the UI. To it, paste the following:


```
[mqtt]
username=pioreactor
password=raspberry
broker_address=
broker_ws_port=9001
broker_port=1883
ws_protocol=ws
use_tls=0

```


Before you save, fill in the broker_address= field with your leader's name (and add .local). Ex:



```
[mqtt]
username=pioreactor
password=raspberry
broker_address=pioreactor_leader.local
broker_ws_port=9001
broker_port=1883
ws_protocol=ws
use_tls=0
```

**Comment by Eleni-Mavro** [comment]
Yes, this solved the problem. Thank you !

From: Cameron Davidson-Pilon ***@***.***>
Date: Thursday, 7 March 2024 at 20.06
To: Pioreactor/pioreactorui ***@***.***>
Cc: Eleni Mavrothalassiti ***@***.***>, Author ***@***.***>
Subject: Re: [Pioreactor/pioreactorui] undefined (reading 'username') (Issue #130)

SSH into your leader, and enter:

nano .pioreactor/config.ini

This is your config.ini that you also see in the UI. To it, paste the following:

[mqtt]

username=pioreactor

password=raspberry

broker_address=

broker_ws_port=9001

broker_port=1883

ws_protocol=ws

use_tls=0



Before you save, fill in the broker_address= field with your leader's name (and add .local). Ex:

[mqtt]

username=pioreactor

password=raspberry

broker_address=pioreactor_leader.local

broker_ws_port=9001

broker_port=1883

ws_protocol=ws

use_tls=0
