### ISSUE TITLE
Pioreactor UI crash

### ISSUE THREAD

**Issue by sharknaro** [Pioreactor/pioreactorui#137]
I have leader image installed. Currently there are no workers added to the leader and I got this error message when I try to go "Pioreactors" section in the UI:

URL: http://pioreactor.local/pioreactors
i.map is not a function

**Comment by CamDavidsonPilon** [comment]
Ah, yes I'm able to replicate this too when _no workers_ are present. I'll fix for a future release - thanks @sharknaro!
