### ISSUE TITLE
YAML schema only allows bool, string or null for default values for settings

### ISSUE THREAD

**Issue by noahsprent** [Pioreactor/pioreactorui#149]
https://github.com/Pioreactor/pioreactorui/blob/d24275fd5eba71f51b721888278e8e5e96c3d120/pioreactorui/structs.py#L12

`class PublishedSettingsDescriptor(Struct, forbid_unknown_fields=True):  # type: ignore
    key: str
    type: t.Literal["numeric", "boolean", "string", "json"]
    display: bool
    description: t.Optional[str] = None
    default: t.Optional[t.Union[str, bool]] = None
    unit: t.Optional[str] = None
    label: t.Optional[str] = None  # if display is false, this isn't needed
    editable: bool = True`

If using a float for a setting then an error might be raised like:

`2024-12-13T18:09:44 | pioreactor/pioreactor01/$experiment/logs/ui/error | {"message":"Yaml error in vernier_fph_bta.yaml: Expected `bool | str | null`, got `float` - at `$.published_settings[1].default`","task":"get_job_contrib","source":"ui","level":"ERROR","timestamp":"2024-12-13T18:09:44.682885Z"}`

I'm not sure if there's a reason not to allow this behaviour? My expected behaviour would have been that the "type" field restricted the allowable types here

**Comment by CamDavidsonPilon** [comment]
As mentioned [in my forum post here](https://forum.pioreactor.com/t/where-is-the-right-place-to-set-defaults-for-settings-in-plugins/594/2?u=camdavidsonpilon), I think the `defaults` field is used only in very specific places, but I can probably move logic to those specific places  and I'll look into deprecating the `default` field. As is, it's probably more confusing that worth it to keep around.
