### ISSUE TITLE
Bug on multiples pages - blank page

### ISSUE THREAD

**Issue by VitorFrost** [Pioreactor/pioreactorui#86]
I just installed the image from https://github.com/pioreactor/pioreactor/releases/latest/download/pioreactor_leader_worker.img.zip
into a SD card, and loaded it on a Raspberri Pi 3B.
Configured it following the official guide (https://docs.pioreactor.com/user_guide/Raspberry%20Pi%20set%20up%20and%20software%20installation).
 When I load the raspberry IP on the browser, I get a very fast blink with the working page, and then, the pages redirects to /overview
 and I get an blank page, with no menu, nothing.
Get this for less then a second: 
![image](https://user-images.githubusercontent.com/5491480/150198346-10776374-f740-46f4-b3de-e9882e226a30.png)
And then, this:
![image](https://user-images.githubusercontent.com/5491480/150198461-09889fce-f810-44e1-9a79-ba790b1a7f9c.png)

**Comment by VitorFrost** [comment]
Testing with /plugins I also get a blank page:

https://user-images.githubusercontent.com/5491480/150199670-b949d65a-39e0-41c8-a7cb-45321ae6ee58.mp4

**Comment by CamDavidsonPilon** [comment]
Hi @VitorFrost, thanks for the report! 

Hm, can you copy-paste what's in the Console? (by right-clicking and selecting `inspect`, then `console` OR `option-command-i` and then `console`). 

I suspect the React app is crashing, but I don't know why!

**Comment by VitorFrost** [comment]
@CamDavidsonPilon here:

```
DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
    React 5
        ai
        callback
        sa
        di
        Su
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        Ur
        ku
        du
        Vr
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        Ur
        Vr
        Hr
        iu
        So
    Cn utilities.js:2
    (assíncrono: promise callback)
    Cn App.jsx:75
    Tu React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        Ur
        Cu
        du
        Vr
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
        Ur
        Vr
        Hr
        hu
        Ju
        render
    555 index.js:9
    i overview:1
    403 main.4fdf7dd9.chunk.js:1
    i overview:1
    t overview:1
    r overview:1
    <anonymous> main.4fdf7dd9.chunk.js:1

DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    Cn utilities.js:2
    (assíncrono: promise callback)
    Cn App.jsx:75
    Tu React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    555 index.js:9
    i overview:1
    403 main.4fdf7dd9.chunk.js:1
    i overview:1
    t overview:1
    r overview:1
    <anonymous> main.4fdf7dd9.chunk.js:1

DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
DOMException: An invalid or illegal string was specified react-dom.production.min.js:216:199
```

**Comment by VitorFrost** [comment]
I am trying to debug it, but I am a really layman in JS
The error is pointing to the line 123 on the file react-dom.production.min.js:
`function jg(){if(!cg&&null!==ag){cg=!0;var a=0;try{var b=ag;gg(99,function(){for(;a<b.length;a++){var c=b[a];do c=c(!0);while(null!==c)}});ag=null}catch(c){throw null!==ag&&(ag=ag.slice(a+1)),Of(Uf,ig),c;}finally{cg=!1}}}var kg=ra.ReactCurrentBatchConfig;function lg(a,b){if(a&&a.defaultProps){b=m({},b);a=a.defaultProps;for(var c in a)void 0===b[c]&&(b[c]=a[c]);return b}return b}var mg=Bf(null),ng=null,og=null,pg=null;function qg(){pg=og=ng=null}`

**Comment by CamDavidsonPilon** [comment]
Hm, unfortunately the js is minified, so it's too hard to decipher. 

One thing to try is to update to the latest UI version (I've included some more error handling in the latest version). From the Raspberry Pi's command line, enter `pio update --ui`

**Comment by CamDavidsonPilon** [comment]
If _that_ command fails, let me know what the output is. There may be a problem with the `~/.pioreactor/conifg.ini` file (a problem there may also be causing the UI problem).

**Comment by VitorFrost** [comment]
> Hm, unfortunately the js is minified, so it's too hard to decipher.
> 
> One thing to try is to update to the latest UI version (I've included some more error handling in the latest version). From the Raspberry Pi's command line, enter `pio update --ui`

Just tried it on Chrome, that's better to read! It shows an error on the mqtt!
**DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.**

`react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at a.value (http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:15483)
    at di (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:691027)
    at Su (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:708146)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at ku (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:704687)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700773)
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at a.value (http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:15483)
    at di (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:691027)
    at Su (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:708146)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at ku (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:704687)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700773)
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at a.value (http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:15483)
    at di (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:691027)
    at Su (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:708146)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at ku (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:704687)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700773)
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at a.value (http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:15483)
    at di (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:691027)
    at Su (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:708146)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at ku (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:704687)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700773)
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at a.value (http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:23014)
    at di (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:691027)
    at Su (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:708146)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at ku (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:704687)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700773)
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at a.value (http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:4566)
    at di (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:691027)
    at Su (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:708146)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at ku (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:704687)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700773)
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:2251
    at Tu (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:709727)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at Cu (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:709188)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700451)
    at http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649937
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
react-dom.production.min.js:216 DOMException: Failed to construct 'WebSocket': The URL 'ws://:9001/mqtt' is invalid.
    at R._doConnect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:33440)
    at R.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:30334)
    at Client.connect (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:50015)
    at http://192.168.15.100/static/js/main.4fdf7dd9.chunk.js:1:843
    at Tu (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:709727)
    at e.unstable_runWithPriority (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:727540)
    at Ur (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649714)
    at Cu (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:709188)
    at du (http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:700451)
    at http://192.168.15.100/static/js/2.7eb25503.chunk.js:2:649937
ai @ react-dom.production.min.js:216
t.callback @ react-dom.production.min.js:216
sa @ react-dom.production.min.js:131
di @ react-dom.production.min.js:220
Su @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
ku @ react-dom.production.min.js:252
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
iu @ react-dom.production.min.js:237
So @ react-dom.production.min.js:170
(anonymous) @ App.jsx:76
Promise.then (async)
(anonymous) @ App.jsx:75
Tu @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
du @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ur @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Hr @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:244
Ju @ react-dom.production.min.js:289
e.render @ react-dom.production.min.js:296
555 @ index.js:9
i @ overview:1
403 @ main.4fdf7dd9.chunk.js:1
i @ overview:1
t @ overview:1
r @ overview:1
(anonymous) @ main.4fdf7dd9.chunk.js:1
`

**Comment by CamDavidsonPilon** [comment]
ahh okay, so I don't know _why_ this happened, but I suspect that the field 
```
[network.topology]
leader_address=
```
is empty in `/home/pi/.pioreactor/config.ini`. If it is empty, it should be `<hostname>.local`.

**Comment by CamDavidsonPilon** [comment]
Also, 
```
[network.topology]
# should be a hostname defined on the network
# See docs: https://docs.pioreactor.com/user_guide/Creating%20a%20Pioreactor%20cluster
leader_hostname=
```

should be populated, too, with your `<your Raspberry Pi's hostname>`. 

So, if your hostname is `leader`, it should look like:

```
[network.topology]
# should be a hostname defined on the network
# See docs: https://docs.pioreactor.com/user_guide/Creating%20a%20Pioreactor%20cluster
leader_hostname=leader

# something like: leadername.local
# this can be an IP address, too.
leader_address=leader.local
```

**Comment by CamDavidsonPilon** [comment]
From what I'm seeing, I suspect the `firstboot.sh` script failed to execute (I'll need to add some logging around this). The `firstboot.sh` runs on the RaspberryPi's first boot up, and does [some of the tasks above for you](https://github.com/Pioreactor/CustoPiZer/blob/pioreactor/workspace/scripts/files/bash/firstboot_leader.sh).

If it successfully ran, there should be a `/boot/firstboot.sh.done` present. If it failed, it would look like `/boot/firstboot.sh`.

**Comment by VitorFrost** [comment]
> From what I'm seeing, I suspect the `firstboot.sh` script failed to execute (I'll need to add some logging around this). The `firstboot.sh` runs on the RaspberryPi's first boot up, and does [some of the tasks above for you](https://github.com/Pioreactor/CustoPiZer/blob/pioreactor/workspace/scripts/files/bash/firstboot_leader.sh).
> 
> If it successfully ran, there should be a `/boot/firstboot.sh.done` present. If it failed, it would look like `/boot/firstboot.sh`.

I was about to report that problem! I always get the error that systemctl could not launch firstboot.
I am just doing a fresh copy of the image just to be sure. in a few minutes, I will be back with more details

**Comment by CamDavidsonPilon** [comment]
If it keeps failing, try running
```
sudo systemctl status firstboot
```

and it may give more details about why it failed
